// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarshipShop.Api.Data;

#nullable disable

namespace StarshipShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217125234_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StarshipShop.Api.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<double>("FuelUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_usage");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("maximum_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("engines");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.FtlDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<double>("FuelUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_usage");

                    b.Property<double>("MaximumSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("maximum_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ftl_drives");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PaymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("card_number");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("payment_details");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentDetailsId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_details_id");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<int>("StarshipId")
                        .HasColumnType("integer")
                        .HasColumnName("starship_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentDetailsId");

                    b.HasIndex("StarshipId");

                    b.HasIndex("UserId");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Starship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EngineId")
                        .HasColumnType("integer")
                        .HasColumnName("engine_id");

                    b.Property<bool>("FtlCapable")
                        .HasColumnType("boolean")
                        .HasColumnName("ftl_capable");

                    b.Property<int?>("FtlDriveId")
                        .HasColumnType("integer")
                        .HasColumnName("ftl_drive_id");

                    b.Property<string>("IconPictureFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_picture_file_path");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("StarshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("starship_type");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<int>("TotalCrew")
                        .HasColumnType("integer")
                        .HasColumnName("total_crew");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("FtlDriveId");

                    b.ToTable("starships");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StarshipShop.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.CargoVessel", b =>
                {
                    b.HasBaseType("StarshipShop.Api.Models.Starship");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo_type");

                    b.Property<int>("TotalCargoCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_cargo_capacity");

                    b.ToTable("cargo_vessels");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PrivateVessel", b =>
                {
                    b.HasBaseType("StarshipShop.Api.Models.Starship");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vessel_type");

                    b.ToTable("private_vessels");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PublicTransportVessel", b =>
                {
                    b.HasBaseType("StarshipShop.Api.Models.Starship");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("integer")
                        .HasColumnName("total_passengers");

                    b.Property<string>("TransportClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_class");

                    b.ToTable("public_transport_vessels");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PaymentDetails", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.User", "User")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Sale", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.PaymentDetails", "PaymentDetails")
                        .WithMany("Sales")
                        .HasForeignKey("PaymentDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarshipShop.Api.Models.Starship", "Starship")
                        .WithMany("Sales")
                        .HasForeignKey("StarshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarshipShop.Api.Models.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentDetails");

                    b.Navigation("Starship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Starship", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.Engine", "Engine")
                        .WithMany("Starships")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarshipShop.Api.Models.FtlDrive", "FtlDrive")
                        .WithMany("Starships")
                        .HasForeignKey("FtlDriveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Engine");

                    b.Navigation("FtlDrive");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.CargoVessel", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.Starship", null)
                        .WithOne()
                        .HasForeignKey("StarshipShop.Api.Models.CargoVessel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PrivateVessel", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.Starship", null)
                        .WithOne()
                        .HasForeignKey("StarshipShop.Api.Models.PrivateVessel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PublicTransportVessel", b =>
                {
                    b.HasOne("StarshipShop.Api.Models.Starship", null)
                        .WithOne()
                        .HasForeignKey("StarshipShop.Api.Models.PublicTransportVessel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Engine", b =>
                {
                    b.Navigation("Starships");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.FtlDrive", b =>
                {
                    b.Navigation("Starships");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.PaymentDetails", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.Starship", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("StarshipShop.Api.Models.User", b =>
                {
                    b.Navigation("PaymentDetails");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
